services:
  postgres_db:
    image: postgres:latest
    networks:
      - please_work
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_POSTGRES}
    volumes:
      - ./postgres_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  mongo_db:
    image: mongo:6
    networks:
      - please_work
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME_MONGO}
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - mongo_db
    networks:
      - please_work

networks:
  please_work:
    name: assignment4
    driver: bridge
